# Generated by Django 4.2.5 on 2023-09-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Date of birth'),
        ),
    ]
